# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    # ----------User------------ 
    App\Repository\UserRepository:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'

    App\Service\UserService:
        arguments:
            $repository: '@App\Repository\UserRepository'

    App\Controller\SignUpContoller:
        arguments:
            $service: '@App\Service\UserService'

    # ----------Order------------
    App\Repository\OrderRepository:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            
    App\Service\OrderService:
        arguments:
            $orderRepository: '@App\Repository\OrderRepository'
            
    App\Controller\OrdersController:
        arguments:
            $service: '@App\Service\OrderService'
            $security: '@Symfony\Component\Security\Core\Security'

    App\Controller\StatusController:
        arguments:
            $service: '@App\Service\OrderService'

    # ---------Query----------
    App\Query\UserQueryService:
        arguments:
            $repository: '@App\Repository\UserRepository'

    App\Query\PizzaQueryService:
        arguments:
            $repository: '@App\Repository\PizzaRepository'
    
    App\Query\OrderQueryService:
        arguments:
            $repository: '@App\Repository\OrderRepository'

    App\Controller\UsersController:
        arguments:
            $query: '@App\Query\UserQueryService'

    App\Controller\HomeController:
        arguments:
            $pizzaQuery: '@App\Query\PizzaQueryService'
            $orderQuery: '@App\Query\OrderQueryService'

            